spring.application.name=springAi
spring.config.import=optional:file:.env[.properties]

spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.api-key=${KEY}
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/pgDb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.allow-bean-definition-overriding=true
spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always